// // AUTOGENERATED FILE — DO NOT EDIT BY HAND.
// //
// // Generated by Pigeon from
// // packages/pyrx_synapse_platform_interface/pigeons/pyrx_synapse_messages.dart.
// // To regenerate, run `melos run pigeon-generate` from the repo root.
// //
// // Copyright (c) 2026 PYRX Tech — MIT License.
// Autogenerated from Pigeon (v27.1.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

enum PyrxSynapseMessagesPigeonInternal {
  static func isNullish(_ value: Any?) -> Bool {
    guard let innerValue = value else {
      return true
    }

    if case Optional<Any>.some(Optional<Any>.none) = value {
      return true
    }

    return innerValue is NSNull
  }
  static func doubleEquals(_ lhs: Double, _ rhs: Double) -> Bool {
    return (lhs.isNaN && rhs.isNaN) || lhs == rhs
  }

  static func doubleHash(_ value: Double, _ hasher: inout Hasher) {
    if value.isNaN {
      hasher.combine(0x7FF8000000000000)
    } else {
      // Normalize -0.0 to 0.0
      hasher.combine(value == 0 ? 0 : value)
    }
  }

  static func deepEquals(_ lhs: Any?, _ rhs: Any?) -> Bool {
    let cleanLhs = nilOrValue(lhs) as Any?
    let cleanRhs = nilOrValue(rhs) as Any?
    switch (cleanLhs, cleanRhs) {
    case (nil, nil):
      return true

    case (nil, _), (_, nil):
      return false

    case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
      return true

    case is (Void, Void):
      return true

    case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !deepEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsArray, let rhsArray) as ([Double], [Double]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !doubleEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
      guard lhsDictionary.count == rhsDictionary.count else { return false }
      for (lhsKey, lhsValue) in lhsDictionary {
        var found = false
        for (rhsKey, rhsValue) in rhsDictionary {
          if deepEquals(lhsKey, rhsKey) {
            if deepEquals(lhsValue, rhsValue) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if !found { return false }
      }
      return true

    case (let lhs as Double, let rhs as Double):
      return doubleEquals(lhs, rhs)

    case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
      return lhsHashable == rhsHashable

    default:
      return false
    }
  }

  static func deepHash(value: Any?, hasher: inout Hasher) {
    let cleanValue = nilOrValue(value) as Any?
    if let cleanValue = cleanValue {
      if let doubleValue = cleanValue as? Double {
        doubleHash(doubleValue, &hasher)
      } else if let valueList = cleanValue as? [Any?] {
        for item in valueList {
          deepHash(value: item, hasher: &hasher)
        }
      } else if let valueList = cleanValue as? [Double] {
        for item in valueList {
          doubleHash(item, &hasher)
        }
      } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
        var result = 0
        for (key, value) in valueDict {
          var entryKeyHasher = Hasher()
          deepHash(value: key, hasher: &entryKeyHasher)
          var entryValueHasher = Hasher()
          deepHash(value: value, hasher: &entryValueHasher)
          result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
        }
        hasher.combine(result)
      } else if let hashableValue = cleanValue as? AnyHashable {
        hasher.combine(hashableValue)
      } else {
        hasher.combine(String(describing: cleanValue))
      }
    } else {
      hasher.combine(0)
    }
  }

}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


/// Discriminator for [PyrxEventEnvelope]. Mirrors the case-set of the
/// native sealed types byte-for-byte.
///
/// Adding new cases is an additive change (per ADR-0005 D5). PR-2's
/// Dart consumer wraps a `default:` branch so unknown variants from
/// future native SDKs are tolerated; the umbrella's `Stream<PyrxEvent>`
/// drops unknown envelopes silently with a debug log.
enum PyrxEventKind: Int, CaseIterable {
  case pushReceived = 0
  case pushClicked = 1
  case pushReceivedColdStart = 2
  case queueDrained = 3
  case identityChanged = 4
}

/// Arguments for [PyrxSynapseHostApi.initialize].
///
/// Mirrors `PyrxConfig` (iOS) and the equivalent Kotlin `PyrxConfig`
/// data class (Android). Flat fields keep the Pigeon codec simple;
/// optional fields cover the "use the SDK default" case.
///
/// Generated class from Pigeon that represents data sent in messages.
struct PyrxInitArgs: Hashable, CustomStringConvertible {
  /// Synapse workspace identifier (UUID v4 string).
  var workspaceId: String
  /// Public ingestion API key. Format: `psk_{env}_{hex32}`.
  var apiKey: String
  /// One of: `"production"`, `"sandbox"`, `"staging"`.
  var environment: String
  /// Optional override for the ingestion base URL. Pass `null` to use
  /// the SDK default for the selected environment.
  var baseUrl: String? = nil
  /// One of: `"debug"`, `"info"`, `"warning"`, `"error"`, `"none"`.
  /// Defaults to `"info"` on the native side if `null`.
  var logLevel: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PyrxInitArgs? {
    let workspaceId = pigeonVar_list[0] as! String
    let apiKey = pigeonVar_list[1] as! String
    let environment = pigeonVar_list[2] as! String
    let baseUrl: String? = nilOrValue(pigeonVar_list[3])
    let logLevel: String? = nilOrValue(pigeonVar_list[4])

    return PyrxInitArgs(
      workspaceId: workspaceId,
      apiKey: apiKey,
      environment: environment,
      baseUrl: baseUrl,
      logLevel: logLevel
    )
  }
  func toList() -> [Any?] {
    return [
      workspaceId,
      apiKey,
      environment,
      baseUrl,
      logLevel,
    ]
  }
  static func == (lhs: PyrxInitArgs, rhs: PyrxInitArgs) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return PyrxSynapseMessagesPigeonInternal.deepEquals(lhs.workspaceId, rhs.workspaceId) && PyrxSynapseMessagesPigeonInternal.deepEquals(lhs.apiKey, rhs.apiKey) && PyrxSynapseMessagesPigeonInternal.deepEquals(lhs.environment, rhs.environment) && PyrxSynapseMessagesPigeonInternal.deepEquals(lhs.baseUrl, rhs.baseUrl) && PyrxSynapseMessagesPigeonInternal.deepEquals(lhs.logLevel, rhs.logLevel)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("PyrxInitArgs")
    PyrxSynapseMessagesPigeonInternal.deepHash(value: workspaceId, hasher: &hasher)
    PyrxSynapseMessagesPigeonInternal.deepHash(value: apiKey, hasher: &hasher)
    PyrxSynapseMessagesPigeonInternal.deepHash(value: environment, hasher: &hasher)
    PyrxSynapseMessagesPigeonInternal.deepHash(value: baseUrl, hasher: &hasher)
    PyrxSynapseMessagesPigeonInternal.deepHash(value: logLevel, hasher: &hasher)
  }

  public var description: String {
    return "PyrxInitArgs(workspaceId: \(String(describing: workspaceId)), apiKey: \(String(describing: apiKey)), environment: \(String(describing: environment)), baseUrl: \(String(describing: baseUrl)), logLevel: \(String(describing: logLevel)))"
  }
}

/// Result of [PyrxSynapseHostApi.identify] and
/// [PyrxSynapseHostApi.alias].
///
/// Mirrors `IdentityResult` on both natives. Used to surface which
/// merge branch ran for support diagnostics.
///
/// Generated class from Pigeon that represents data sent in messages.
struct PyrxIdentityResult: Hashable, CustomStringConvertible {
  /// Server-assigned contact UUID.
  var contactId: String
  /// One of: `"new"`, `"merge"`, `"alias"`, `"noop"`.
  var path: String
  /// For `alias` results, the prior `externalId` that was merged in.
  /// Null for `identify` calls.
  var aliasedExternalId: String? = nil
  var eventsReattributed: Int64
  var devicesReattributed: Int64


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PyrxIdentityResult? {
    let contactId = pigeonVar_list[0] as! String
    let path = pigeonVar_list[1] as! String
    let aliasedExternalId: String? = nilOrValue(pigeonVar_list[2])
    let eventsReattributed = pigeonVar_list[3] as! Int64
    let devicesReattributed = pigeonVar_list[4] as! Int64

    return PyrxIdentityResult(
      contactId: contactId,
      path: path,
      aliasedExternalId: aliasedExternalId,
      eventsReattributed: eventsReattributed,
      devicesReattributed: devicesReattributed
    )
  }
  func toList() -> [Any?] {
    return [
      contactId,
      path,
      aliasedExternalId,
      eventsReattributed,
      devicesReattributed,
    ]
  }
  static func == (lhs: PyrxIdentityResult, rhs: PyrxIdentityResult) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return PyrxSynapseMessagesPigeonInternal.deepEquals(lhs.contactId, rhs.contactId) && PyrxSynapseMessagesPigeonInternal.deepEquals(lhs.path, rhs.path) && PyrxSynapseMessagesPigeonInternal.deepEquals(lhs.aliasedExternalId, rhs.aliasedExternalId) && PyrxSynapseMessagesPigeonInternal.deepEquals(lhs.eventsReattributed, rhs.eventsReattributed) && PyrxSynapseMessagesPigeonInternal.deepEquals(lhs.devicesReattributed, rhs.devicesReattributed)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("PyrxIdentityResult")
    PyrxSynapseMessagesPigeonInternal.deepHash(value: contactId, hasher: &hasher)
    PyrxSynapseMessagesPigeonInternal.deepHash(value: path, hasher: &hasher)
    PyrxSynapseMessagesPigeonInternal.deepHash(value: aliasedExternalId, hasher: &hasher)
    PyrxSynapseMessagesPigeonInternal.deepHash(value: eventsReattributed, hasher: &hasher)
    PyrxSynapseMessagesPigeonInternal.deepHash(value: devicesReattributed, hasher: &hasher)
  }

  public var description: String {
    return "PyrxIdentityResult(contactId: \(String(describing: contactId)), path: \(String(describing: path)), aliasedExternalId: \(String(describing: aliasedExternalId)), eventsReattributed: \(String(describing: eventsReattributed)), devicesReattributed: \(String(describing: devicesReattributed)))"
  }
}

/// Result of [PyrxSynapseHostApi.requestPushPermission].
///
/// Mirrors the OS-level permission verdict. Android maps Android 13+'s
/// runtime POST_NOTIFICATIONS result and "granted by default" on
/// older OS versions.
///
/// Generated class from Pigeon that represents data sent in messages.
struct PyrxPushPermissionResult: Hashable, CustomStringConvertible {
  /// One of: `"granted"`, `"denied"`, `"provisional"`, `"notDetermined"`.
  var status: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PyrxPushPermissionResult? {
    let status = pigeonVar_list[0] as! String

    return PyrxPushPermissionResult(
      status: status
    )
  }
  func toList() -> [Any?] {
    return [
      status
    ]
  }
  static func == (lhs: PyrxPushPermissionResult, rhs: PyrxPushPermissionResult) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return PyrxSynapseMessagesPigeonInternal.deepEquals(lhs.status, rhs.status)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("PyrxPushPermissionResult")
    PyrxSynapseMessagesPigeonInternal.deepHash(value: status, hasher: &hasher)
  }

  public var description: String {
    return "PyrxPushPermissionResult(status: \(String(describing: status)))"
  }
}

/// Snapshot returned by [PyrxSynapseHostApi.debugInfo].
///
/// Mirrors `PyrxDebugInfo` on both natives. Used by customer support
/// and `/debug` screens.
///
/// Generated class from Pigeon that represents data sent in messages.
struct PyrxDebugInfo: Hashable, CustomStringConvertible {
  var sdkVersion: String
  var platform: String
  var initialized: Bool
  var workspaceId: String? = nil
  var environment: String? = nil
  var baseUrl: String? = nil
  var logLevel: String
  var anonymousId: String? = nil
  var externalId: String? = nil
  var trackingEnabled: Bool
  var queueDepth: Int64
  var deviceTokenFingerprint: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PyrxDebugInfo? {
    let sdkVersion = pigeonVar_list[0] as! String
    let platform = pigeonVar_list[1] as! String
    let initialized = pigeonVar_list[2] as! Bool
    let workspaceId: String? = nilOrValue(pigeonVar_list[3])
    let environment: String? = nilOrValue(pigeonVar_list[4])
    let baseUrl: String? = nilOrValue(pigeonVar_list[5])
    let logLevel = pigeonVar_list[6] as! String
    let anonymousId: String? = nilOrValue(pigeonVar_list[7])
    let externalId: String? = nilOrValue(pigeonVar_list[8])
    let trackingEnabled = pigeonVar_list[9] as! Bool
    let queueDepth = pigeonVar_list[10] as! Int64
    let deviceTokenFingerprint: String? = nilOrValue(pigeonVar_list[11])

    return PyrxDebugInfo(
      sdkVersion: sdkVersion,
      platform: platform,
      initialized: initialized,
      workspaceId: workspaceId,
      environment: environment,
      baseUrl: baseUrl,
      logLevel: logLevel,
      anonymousId: anonymousId,
      externalId: externalId,
      trackingEnabled: trackingEnabled,
      queueDepth: queueDepth,
      deviceTokenFingerprint: deviceTokenFingerprint
    )
  }
  func toList() -> [Any?] {
    return [
      sdkVersion,
      platform,
      initialized,
      workspaceId,
      environment,
      baseUrl,
      logLevel,
      anonymousId,
      externalId,
      trackingEnabled,
      queueDepth,
      deviceTokenFingerprint,
    ]
  }
  static func == (lhs: PyrxDebugInfo, rhs: PyrxDebugInfo) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return PyrxSynapseMessagesPigeonInternal.deepEquals(lhs.sdkVersion, rhs.sdkVersion) && PyrxSynapseMessagesPigeonInternal.deepEquals(lhs.platform, rhs.platform) && PyrxSynapseMessagesPigeonInternal.deepEquals(lhs.initialized, rhs.initialized) && PyrxSynapseMessagesPigeonInternal.deepEquals(lhs.workspaceId, rhs.workspaceId) && PyrxSynapseMessagesPigeonInternal.deepEquals(lhs.environment, rhs.environment) && PyrxSynapseMessagesPigeonInternal.deepEquals(lhs.baseUrl, rhs.baseUrl) && PyrxSynapseMessagesPigeonInternal.deepEquals(lhs.logLevel, rhs.logLevel) && PyrxSynapseMessagesPigeonInternal.deepEquals(lhs.anonymousId, rhs.anonymousId) && PyrxSynapseMessagesPigeonInternal.deepEquals(lhs.externalId, rhs.externalId) && PyrxSynapseMessagesPigeonInternal.deepEquals(lhs.trackingEnabled, rhs.trackingEnabled) && PyrxSynapseMessagesPigeonInternal.deepEquals(lhs.queueDepth, rhs.queueDepth) && PyrxSynapseMessagesPigeonInternal.deepEquals(lhs.deviceTokenFingerprint, rhs.deviceTokenFingerprint)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("PyrxDebugInfo")
    PyrxSynapseMessagesPigeonInternal.deepHash(value: sdkVersion, hasher: &hasher)
    PyrxSynapseMessagesPigeonInternal.deepHash(value: platform, hasher: &hasher)
    PyrxSynapseMessagesPigeonInternal.deepHash(value: initialized, hasher: &hasher)
    PyrxSynapseMessagesPigeonInternal.deepHash(value: workspaceId, hasher: &hasher)
    PyrxSynapseMessagesPigeonInternal.deepHash(value: environment, hasher: &hasher)
    PyrxSynapseMessagesPigeonInternal.deepHash(value: baseUrl, hasher: &hasher)
    PyrxSynapseMessagesPigeonInternal.deepHash(value: logLevel, hasher: &hasher)
    PyrxSynapseMessagesPigeonInternal.deepHash(value: anonymousId, hasher: &hasher)
    PyrxSynapseMessagesPigeonInternal.deepHash(value: externalId, hasher: &hasher)
    PyrxSynapseMessagesPigeonInternal.deepHash(value: trackingEnabled, hasher: &hasher)
    PyrxSynapseMessagesPigeonInternal.deepHash(value: queueDepth, hasher: &hasher)
    PyrxSynapseMessagesPigeonInternal.deepHash(value: deviceTokenFingerprint, hasher: &hasher)
  }

  public var description: String {
    return "PyrxDebugInfo(sdkVersion: \(String(describing: sdkVersion)), platform: \(String(describing: platform)), initialized: \(String(describing: initialized)), workspaceId: \(String(describing: workspaceId)), environment: \(String(describing: environment)), baseUrl: \(String(describing: baseUrl)), logLevel: \(String(describing: logLevel)), anonymousId: \(String(describing: anonymousId)), externalId: \(String(describing: externalId)), trackingEnabled: \(String(describing: trackingEnabled)), queueDepth: \(String(describing: queueDepth)), deviceTokenFingerprint: \(String(describing: deviceTokenFingerprint)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct PushReceivedEventDto: Hashable, CustomStringConvertible {
  var title: String
  var body: String
  var pushLogId: String? = nil
  var data: [String?: Any?]
  var pyrxAttrs: [String?: Any?]? = nil
  /// ISO-8601 UTC timestamp from the native delegate.
  var receivedAt: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PushReceivedEventDto? {
    let title = pigeonVar_list[0] as! String
    let body = pigeonVar_list[1] as! String
    let pushLogId: String? = nilOrValue(pigeonVar_list[2])
    let data = pigeonVar_list[3] as! [String?: Any?]
    let pyrxAttrs: [String?: Any?]? = nilOrValue(pigeonVar_list[4])
    let receivedAt = pigeonVar_list[5] as! String

    return PushReceivedEventDto(
      title: title,
      body: body,
      pushLogId: pushLogId,
      data: data,
      pyrxAttrs: pyrxAttrs,
      receivedAt: receivedAt
    )
  }
  func toList() -> [Any?] {
    return [
      title,
      body,
      pushLogId,
      data,
      pyrxAttrs,
      receivedAt,
    ]
  }
  static func == (lhs: PushReceivedEventDto, rhs: PushReceivedEventDto) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return PyrxSynapseMessagesPigeonInternal.deepEquals(lhs.title, rhs.title) && PyrxSynapseMessagesPigeonInternal.deepEquals(lhs.body, rhs.body) && PyrxSynapseMessagesPigeonInternal.deepEquals(lhs.pushLogId, rhs.pushLogId) && PyrxSynapseMessagesPigeonInternal.deepEquals(lhs.data, rhs.data) && PyrxSynapseMessagesPigeonInternal.deepEquals(lhs.pyrxAttrs, rhs.pyrxAttrs) && PyrxSynapseMessagesPigeonInternal.deepEquals(lhs.receivedAt, rhs.receivedAt)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("PushReceivedEventDto")
    PyrxSynapseMessagesPigeonInternal.deepHash(value: title, hasher: &hasher)
    PyrxSynapseMessagesPigeonInternal.deepHash(value: body, hasher: &hasher)
    PyrxSynapseMessagesPigeonInternal.deepHash(value: pushLogId, hasher: &hasher)
    PyrxSynapseMessagesPigeonInternal.deepHash(value: data, hasher: &hasher)
    PyrxSynapseMessagesPigeonInternal.deepHash(value: pyrxAttrs, hasher: &hasher)
    PyrxSynapseMessagesPigeonInternal.deepHash(value: receivedAt, hasher: &hasher)
  }

  public var description: String {
    return "PushReceivedEventDto(title: \(String(describing: title)), body: \(String(describing: body)), pushLogId: \(String(describing: pushLogId)), data: \(String(describing: data)), pyrxAttrs: \(String(describing: pyrxAttrs)), receivedAt: \(String(describing: receivedAt)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct PushClickedEventDto: Hashable, CustomStringConvertible {
  var pushLogId: String? = nil
  var deepLink: String? = nil
  var actionId: String? = nil
  var pyrxAttrs: [String?: Any?]? = nil
  var clickedAt: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PushClickedEventDto? {
    let pushLogId: String? = nilOrValue(pigeonVar_list[0])
    let deepLink: String? = nilOrValue(pigeonVar_list[1])
    let actionId: String? = nilOrValue(pigeonVar_list[2])
    let pyrxAttrs: [String?: Any?]? = nilOrValue(pigeonVar_list[3])
    let clickedAt = pigeonVar_list[4] as! String

    return PushClickedEventDto(
      pushLogId: pushLogId,
      deepLink: deepLink,
      actionId: actionId,
      pyrxAttrs: pyrxAttrs,
      clickedAt: clickedAt
    )
  }
  func toList() -> [Any?] {
    return [
      pushLogId,
      deepLink,
      actionId,
      pyrxAttrs,
      clickedAt,
    ]
  }
  static func == (lhs: PushClickedEventDto, rhs: PushClickedEventDto) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return PyrxSynapseMessagesPigeonInternal.deepEquals(lhs.pushLogId, rhs.pushLogId) && PyrxSynapseMessagesPigeonInternal.deepEquals(lhs.deepLink, rhs.deepLink) && PyrxSynapseMessagesPigeonInternal.deepEquals(lhs.actionId, rhs.actionId) && PyrxSynapseMessagesPigeonInternal.deepEquals(lhs.pyrxAttrs, rhs.pyrxAttrs) && PyrxSynapseMessagesPigeonInternal.deepEquals(lhs.clickedAt, rhs.clickedAt)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("PushClickedEventDto")
    PyrxSynapseMessagesPigeonInternal.deepHash(value: pushLogId, hasher: &hasher)
    PyrxSynapseMessagesPigeonInternal.deepHash(value: deepLink, hasher: &hasher)
    PyrxSynapseMessagesPigeonInternal.deepHash(value: actionId, hasher: &hasher)
    PyrxSynapseMessagesPigeonInternal.deepHash(value: pyrxAttrs, hasher: &hasher)
    PyrxSynapseMessagesPigeonInternal.deepHash(value: clickedAt, hasher: &hasher)
  }

  public var description: String {
    return "PushClickedEventDto(pushLogId: \(String(describing: pushLogId)), deepLink: \(String(describing: deepLink)), actionId: \(String(describing: actionId)), pyrxAttrs: \(String(describing: pyrxAttrs)), clickedAt: \(String(describing: clickedAt)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct IdentitySnapshotDto: Hashable, CustomStringConvertible {
  var anonymousId: String? = nil
  var externalId: String? = nil
  var snapshotAt: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> IdentitySnapshotDto? {
    let anonymousId: String? = nilOrValue(pigeonVar_list[0])
    let externalId: String? = nilOrValue(pigeonVar_list[1])
    let snapshotAt = pigeonVar_list[2] as! String

    return IdentitySnapshotDto(
      anonymousId: anonymousId,
      externalId: externalId,
      snapshotAt: snapshotAt
    )
  }
  func toList() -> [Any?] {
    return [
      anonymousId,
      externalId,
      snapshotAt,
    ]
  }
  static func == (lhs: IdentitySnapshotDto, rhs: IdentitySnapshotDto) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return PyrxSynapseMessagesPigeonInternal.deepEquals(lhs.anonymousId, rhs.anonymousId) && PyrxSynapseMessagesPigeonInternal.deepEquals(lhs.externalId, rhs.externalId) && PyrxSynapseMessagesPigeonInternal.deepEquals(lhs.snapshotAt, rhs.snapshotAt)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("IdentitySnapshotDto")
    PyrxSynapseMessagesPigeonInternal.deepHash(value: anonymousId, hasher: &hasher)
    PyrxSynapseMessagesPigeonInternal.deepHash(value: externalId, hasher: &hasher)
    PyrxSynapseMessagesPigeonInternal.deepHash(value: snapshotAt, hasher: &hasher)
  }

  public var description: String {
    return "IdentitySnapshotDto(anonymousId: \(String(describing: anonymousId)), externalId: \(String(describing: externalId)), snapshotAt: \(String(describing: snapshotAt)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct QueueDrainedEventDto: Hashable, CustomStringConvertible {
  var count: Int64


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> QueueDrainedEventDto? {
    let count = pigeonVar_list[0] as! Int64

    return QueueDrainedEventDto(
      count: count
    )
  }
  func toList() -> [Any?] {
    return [
      count
    ]
  }
  static func == (lhs: QueueDrainedEventDto, rhs: QueueDrainedEventDto) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return PyrxSynapseMessagesPigeonInternal.deepEquals(lhs.count, rhs.count)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("QueueDrainedEventDto")
    PyrxSynapseMessagesPigeonInternal.deepHash(value: count, hasher: &hasher)
  }

  public var description: String {
    return "QueueDrainedEventDto(count: \(String(describing: count)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct IdentityChangedEventDto: Hashable, CustomStringConvertible {
  var before: IdentitySnapshotDto? = nil
  var after: IdentitySnapshotDto


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> IdentityChangedEventDto? {
    let before: IdentitySnapshotDto? = nilOrValue(pigeonVar_list[0])
    let after = pigeonVar_list[1] as! IdentitySnapshotDto

    return IdentityChangedEventDto(
      before: before,
      after: after
    )
  }
  func toList() -> [Any?] {
    return [
      before,
      after,
    ]
  }
  static func == (lhs: IdentityChangedEventDto, rhs: IdentityChangedEventDto) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return PyrxSynapseMessagesPigeonInternal.deepEquals(lhs.before, rhs.before) && PyrxSynapseMessagesPigeonInternal.deepEquals(lhs.after, rhs.after)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("IdentityChangedEventDto")
    PyrxSynapseMessagesPigeonInternal.deepHash(value: before, hasher: &hasher)
    PyrxSynapseMessagesPigeonInternal.deepHash(value: after, hasher: &hasher)
  }

  public var description: String {
    return "IdentityChangedEventDto(before: \(String(describing: before)), after: \(String(describing: after)))"
  }
}

/// Single wire envelope for the 5-event observer surface. Exactly one of
/// the `*Payload` fields is non-null per envelope, matching [kind].
///
/// We use a flat-fields envelope instead of a Dart sealed class so
/// Pigeon's codec stays straightforward — Pigeon does not yet support
/// sealed-class generation across all three target languages.
///
/// Generated class from Pigeon that represents data sent in messages.
struct PyrxEventEnvelope: Hashable, CustomStringConvertible {
  var kind: PyrxEventKind
  var pushReceived: PushReceivedEventDto? = nil
  var pushClicked: PushClickedEventDto? = nil
  var pushReceivedColdStart: PushReceivedEventDto? = nil
  var queueDrained: QueueDrainedEventDto? = nil
  var identityChanged: IdentityChangedEventDto? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PyrxEventEnvelope? {
    let kind = pigeonVar_list[0] as! PyrxEventKind
    let pushReceived: PushReceivedEventDto? = nilOrValue(pigeonVar_list[1])
    let pushClicked: PushClickedEventDto? = nilOrValue(pigeonVar_list[2])
    let pushReceivedColdStart: PushReceivedEventDto? = nilOrValue(pigeonVar_list[3])
    let queueDrained: QueueDrainedEventDto? = nilOrValue(pigeonVar_list[4])
    let identityChanged: IdentityChangedEventDto? = nilOrValue(pigeonVar_list[5])

    return PyrxEventEnvelope(
      kind: kind,
      pushReceived: pushReceived,
      pushClicked: pushClicked,
      pushReceivedColdStart: pushReceivedColdStart,
      queueDrained: queueDrained,
      identityChanged: identityChanged
    )
  }
  func toList() -> [Any?] {
    return [
      kind,
      pushReceived,
      pushClicked,
      pushReceivedColdStart,
      queueDrained,
      identityChanged,
    ]
  }
  static func == (lhs: PyrxEventEnvelope, rhs: PyrxEventEnvelope) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return PyrxSynapseMessagesPigeonInternal.deepEquals(lhs.kind, rhs.kind) && PyrxSynapseMessagesPigeonInternal.deepEquals(lhs.pushReceived, rhs.pushReceived) && PyrxSynapseMessagesPigeonInternal.deepEquals(lhs.pushClicked, rhs.pushClicked) && PyrxSynapseMessagesPigeonInternal.deepEquals(lhs.pushReceivedColdStart, rhs.pushReceivedColdStart) && PyrxSynapseMessagesPigeonInternal.deepEquals(lhs.queueDrained, rhs.queueDrained) && PyrxSynapseMessagesPigeonInternal.deepEquals(lhs.identityChanged, rhs.identityChanged)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("PyrxEventEnvelope")
    PyrxSynapseMessagesPigeonInternal.deepHash(value: kind, hasher: &hasher)
    PyrxSynapseMessagesPigeonInternal.deepHash(value: pushReceived, hasher: &hasher)
    PyrxSynapseMessagesPigeonInternal.deepHash(value: pushClicked, hasher: &hasher)
    PyrxSynapseMessagesPigeonInternal.deepHash(value: pushReceivedColdStart, hasher: &hasher)
    PyrxSynapseMessagesPigeonInternal.deepHash(value: queueDrained, hasher: &hasher)
    PyrxSynapseMessagesPigeonInternal.deepHash(value: identityChanged, hasher: &hasher)
  }

  public var description: String {
    return "PyrxEventEnvelope(kind: \(String(describing: kind)), pushReceived: \(String(describing: pushReceived)), pushClicked: \(String(describing: pushClicked)), pushReceivedColdStart: \(String(describing: pushReceivedColdStart)), queueDrained: \(String(describing: queueDrained)), identityChanged: \(String(describing: identityChanged)))"
  }
}

private class PyrxSynapseMessagesPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return PyrxEventKind(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      return PyrxInitArgs.fromList(self.readValue() as! [Any?])
    case 131:
      return PyrxIdentityResult.fromList(self.readValue() as! [Any?])
    case 132:
      return PyrxPushPermissionResult.fromList(self.readValue() as! [Any?])
    case 133:
      return PyrxDebugInfo.fromList(self.readValue() as! [Any?])
    case 134:
      return PushReceivedEventDto.fromList(self.readValue() as! [Any?])
    case 135:
      return PushClickedEventDto.fromList(self.readValue() as! [Any?])
    case 136:
      return IdentitySnapshotDto.fromList(self.readValue() as! [Any?])
    case 137:
      return QueueDrainedEventDto.fromList(self.readValue() as! [Any?])
    case 138:
      return IdentityChangedEventDto.fromList(self.readValue() as! [Any?])
    case 139:
      return PyrxEventEnvelope.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class PyrxSynapseMessagesPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? PyrxEventKind {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? PyrxInitArgs {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else if let value = value as? PyrxIdentityResult {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else if let value = value as? PyrxPushPermissionResult {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else if let value = value as? PyrxDebugInfo {
      super.writeByte(133)
      super.writeValue(value.toList())
    } else if let value = value as? PushReceivedEventDto {
      super.writeByte(134)
      super.writeValue(value.toList())
    } else if let value = value as? PushClickedEventDto {
      super.writeByte(135)
      super.writeValue(value.toList())
    } else if let value = value as? IdentitySnapshotDto {
      super.writeByte(136)
      super.writeValue(value.toList())
    } else if let value = value as? QueueDrainedEventDto {
      super.writeByte(137)
      super.writeValue(value.toList())
    } else if let value = value as? IdentityChangedEventDto {
      super.writeByte(138)
      super.writeValue(value.toList())
    } else if let value = value as? PyrxEventEnvelope {
      super.writeByte(139)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class PyrxSynapseMessagesPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return PyrxSynapseMessagesPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return PyrxSynapseMessagesPigeonCodecWriter(data: data)
  }
}

class PyrxSynapseMessagesPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = PyrxSynapseMessagesPigeonCodec(readerWriter: PyrxSynapseMessagesPigeonCodecReaderWriter())
}

var pyrxSynapseMessagesPigeonMethodCodec = FlutterStandardMethodCodec(readerWriter: PyrxSynapseMessagesPigeonCodecReaderWriter());


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol PyrxSynapseHostApi {
  func initialize(args: PyrxInitArgs, completion: @escaping (Result<Void, Error>) -> Void)
  func setLogLevel(level: String, completion: @escaping (Result<Void, Error>) -> Void)
  func debugInfo(completion: @escaping (Result<PyrxDebugInfo, Error>) -> Void)
  /// [traitsJson] is a JSON-encoded `Map<String, Object?>` (or null). We
  /// pass JSON-as-string instead of a typed map because Pigeon's
  /// codec rejects deeply nested heterogeneous maps; serialising on
  /// the Dart side keeps the contract narrow and round-trip-stable.
  func identify(externalId: String, traitsJson: String?, completion: @escaping (Result<PyrxIdentityResult, Error>) -> Void)
  func alias(newExternalId: String, completion: @escaping (Result<PyrxIdentityResult, Error>) -> Void)
  func logout(completion: @escaping (Result<Void, Error>) -> Void)
  func track(eventName: String, propertiesJson: String?, completion: @escaping (Result<Void, Error>) -> Void)
  func screen(screenName: String, propertiesJson: String?, completion: @escaping (Result<Void, Error>) -> Void)
  func requestPushPermission(alert: Bool, sound: Bool, badge: Bool, completion: @escaping (Result<PyrxPushPermissionResult, Error>) -> Void)
  /// Trigger an explicit APNs/FCM token registration. On iOS this calls
  /// `UIApplication.shared.registerForRemoteNotifications()`; on Android
  /// this is a no-op (FCM auto-registers via the messaging service).
  func registerForPushNotifications(completion: @escaping (Result<Void, Error>) -> Void)
  func setTrackingEnabled(enabled: Bool, completion: @escaping (Result<Void, Error>) -> Void)
  func deleteUser(completion: @escaping (Result<Void, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class PyrxSynapseHostApiSetup {
  static var codec: FlutterStandardMessageCodec { PyrxSynapseMessagesPigeonCodec.shared }
  /// Sets up an instance of `PyrxSynapseHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: PyrxSynapseHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let initializeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.pyrx_synapse_platform_interface.PyrxSynapseHostApi.initialize\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      initializeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let argsArg = args[0] as! PyrxInitArgs
        api.initialize(args: argsArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      initializeChannel.setMessageHandler(nil)
    }
    let setLogLevelChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.pyrx_synapse_platform_interface.PyrxSynapseHostApi.setLogLevel\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setLogLevelChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let levelArg = args[0] as! String
        api.setLogLevel(level: levelArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      setLogLevelChannel.setMessageHandler(nil)
    }
    let debugInfoChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.pyrx_synapse_platform_interface.PyrxSynapseHostApi.debugInfo\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      debugInfoChannel.setMessageHandler { _, reply in
        api.debugInfo { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      debugInfoChannel.setMessageHandler(nil)
    }
    /// [traitsJson] is a JSON-encoded `Map<String, Object?>` (or null). We
    /// pass JSON-as-string instead of a typed map because Pigeon's
    /// codec rejects deeply nested heterogeneous maps; serialising on
    /// the Dart side keeps the contract narrow and round-trip-stable.
    let identifyChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.pyrx_synapse_platform_interface.PyrxSynapseHostApi.identify\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      identifyChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let externalIdArg = args[0] as! String
        let traitsJsonArg: String? = nilOrValue(args[1])
        api.identify(externalId: externalIdArg, traitsJson: traitsJsonArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      identifyChannel.setMessageHandler(nil)
    }
    let aliasChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.pyrx_synapse_platform_interface.PyrxSynapseHostApi.alias\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      aliasChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let newExternalIdArg = args[0] as! String
        api.alias(newExternalId: newExternalIdArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      aliasChannel.setMessageHandler(nil)
    }
    let logoutChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.pyrx_synapse_platform_interface.PyrxSynapseHostApi.logout\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      logoutChannel.setMessageHandler { _, reply in
        api.logout { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      logoutChannel.setMessageHandler(nil)
    }
    let trackChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.pyrx_synapse_platform_interface.PyrxSynapseHostApi.track\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      trackChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let eventNameArg = args[0] as! String
        let propertiesJsonArg: String? = nilOrValue(args[1])
        api.track(eventName: eventNameArg, propertiesJson: propertiesJsonArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      trackChannel.setMessageHandler(nil)
    }
    let screenChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.pyrx_synapse_platform_interface.PyrxSynapseHostApi.screen\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      screenChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let screenNameArg = args[0] as! String
        let propertiesJsonArg: String? = nilOrValue(args[1])
        api.screen(screenName: screenNameArg, propertiesJson: propertiesJsonArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      screenChannel.setMessageHandler(nil)
    }
    let requestPushPermissionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.pyrx_synapse_platform_interface.PyrxSynapseHostApi.requestPushPermission\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      requestPushPermissionChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let alertArg = args[0] as! Bool
        let soundArg = args[1] as! Bool
        let badgeArg = args[2] as! Bool
        api.requestPushPermission(alert: alertArg, sound: soundArg, badge: badgeArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      requestPushPermissionChannel.setMessageHandler(nil)
    }
    /// Trigger an explicit APNs/FCM token registration. On iOS this calls
    /// `UIApplication.shared.registerForRemoteNotifications()`; on Android
    /// this is a no-op (FCM auto-registers via the messaging service).
    let registerForPushNotificationsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.pyrx_synapse_platform_interface.PyrxSynapseHostApi.registerForPushNotifications\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      registerForPushNotificationsChannel.setMessageHandler { _, reply in
        api.registerForPushNotifications { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      registerForPushNotificationsChannel.setMessageHandler(nil)
    }
    let setTrackingEnabledChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.pyrx_synapse_platform_interface.PyrxSynapseHostApi.setTrackingEnabled\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setTrackingEnabledChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let enabledArg = args[0] as! Bool
        api.setTrackingEnabled(enabled: enabledArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      setTrackingEnabledChannel.setMessageHandler(nil)
    }
    let deleteUserChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.pyrx_synapse_platform_interface.PyrxSynapseHostApi.deleteUser\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      deleteUserChannel.setMessageHandler { _, reply in
        api.deleteUser { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      deleteUserChannel.setMessageHandler(nil)
    }
  }
}

private class PigeonStreamHandler<ReturnType>: NSObject, FlutterStreamHandler {
  private let wrapper: PigeonEventChannelWrapper<ReturnType>
  private var pigeonSink: PigeonEventSink<ReturnType>? = nil

  init(wrapper: PigeonEventChannelWrapper<ReturnType>) {
    self.wrapper = wrapper
  }

  func onListen(withArguments arguments: Any?, eventSink events: @escaping FlutterEventSink)
    -> FlutterError?
  {
    pigeonSink = PigeonEventSink<ReturnType>(events)
    wrapper.onListen(withArguments: arguments, sink: pigeonSink!)
    return nil
  }

  func onCancel(withArguments arguments: Any?) -> FlutterError? {
    pigeonSink = nil
    wrapper.onCancel(withArguments: arguments)
    return nil
  }
}

class PigeonEventChannelWrapper<ReturnType> {
  func onListen(withArguments arguments: Any?, sink: PigeonEventSink<ReturnType>) {}
  func onCancel(withArguments arguments: Any?) {}
}

class PigeonEventSink<ReturnType> {
  private let sink: FlutterEventSink

  init(_ sink: @escaping FlutterEventSink) {
    self.sink = sink
  }

  func success(_ value: ReturnType) {
    sink(value)
  }

  func error(code: String, message: String?, details: Any?) {
    sink(FlutterError(code: code, message: message, details: details))
  }

  func endOfStream() {
    sink(FlutterEndOfEventStream)
  }

}

class StreamEventsStreamHandler: PigeonEventChannelWrapper<PyrxEventEnvelope> {
  static func register(with messenger: FlutterBinaryMessenger,
                      instanceName: String = "",
                      streamHandler: StreamEventsStreamHandler) {
    var channelName = "dev.flutter.pigeon.pyrx_synapse_platform_interface.PyrxSynapseEventApi.streamEvents"
    if !instanceName.isEmpty {
      channelName += ".\(instanceName)"
    }
    let internalStreamHandler = PigeonStreamHandler<PyrxEventEnvelope>(wrapper: streamHandler)
    let channel = FlutterEventChannel(name: channelName, binaryMessenger: messenger, codec: pyrxSynapseMessagesPigeonMethodCodec)
    channel.setStreamHandler(internalStreamHandler)
  }
}
      
